using System.Collections.Generic;
using RealityRoost.Shared.Core;
using Unity.XR.CoreUtils;
using UnityEngine;
using UnityEngine.XR;

namespace RealityRoost.Client.SpatialCalibration
{
    // Workaround for Unity OpenXR plugin bug: the OpenXR runtime regenerates the tracking origin on
    // an HMD recenter even with OpenXRSettings.SetAllowRecentering(false). Since the head cannot
    // physically move during a tracking-origin change, the head pose jump across the event is the
    // old->new tracking-space mapping (yaw + translation only; both spaces are gravity-aligned thanks to OpenXR).
    // Re-expressing the calibrator's raw corners through that same mapping keeps the world aligned after a recenter
    //
    // Sits alongside RRSpatialCalibrator on the rig root.
    [RequireComponent(typeof(XROrigin))]
    public class RRTrackingOriginCompensator : RRSubsystem
    {
        protected override string SubsystemName => "OriginCompensator";

        [Tooltip("Calibrator whose raw corners get re-expressed across a tracking-origin change. Defaults to the component on this GameObject.")]
        [SerializeField] private RRSpatialCalibrator calibrator;


        private XROrigin _xrOrigin;
        private readonly List<XRInputSubsystem> _inputSubsystems = new List<XRInputSubsystem>();

        // Head pose in tracking space, cached at the end of every frame so the pre-event pose is
        // available when the tracking origin regenerates.
        private bool _originChangePending;
        private Vector3 _lastHeadPos;
        private float _lastHeadYawDeg;
        private bool _hasHeadPose;

        protected override void OnSubsystemAwake()
        {
            _xrOrigin = GetComponent<XROrigin>();
            if (calibrator == null)
            {
                calibrator = GetComponent<RRSpatialCalibrator>();
            }
        }

        protected override void OnSubsystemStart()
        {
            SubsystemManager.GetSubsystems(_inputSubsystems);
            foreach (XRInputSubsystem subsystem in _inputSubsystems)
            {
                subsystem.trackingOriginUpdated += OnTrackingOriginUpdated;
            }
        }

        protected override void OnSubsystemStop()
        {
            foreach (XRInputSubsystem subsystem in _inputSubsystems)
            {
                subsystem.trackingOriginUpdated -= OnTrackingOriginUpdated;
            }
            _inputSubsystems.Clear();
        }

        private void OnTrackingOriginUpdated(XRInputSubsystem subsystem)
        {
            if (calibrator != null && calibrator.IsCalibrated && _hasHeadPose)
            {
                // Poses may not be re-expressed in the new space yet
                // Compensate in LateUpdate, once the TrackedPoseDriver has written the post-event head pose
                _originChangePending = true;
                return;
            }
            LogWarning("Tracking origin was regenerated by the runtime/plugin; spatial calibration may have shifted. Re-verify against the physical railing.");
        }

        private void CompensateOriginChange()
        {
            if (calibrator == null)
            {
                return;
            }

            if (!TryGetHeadPoseInTrackingSpace(out Vector3 newHeadPos, out float newHeadYawDeg))
            {
                LogWarning("Tracking origin changed but the head pose is currently unavailable, so cannot compensate. Re-verify against the physical railing.");
                return;
            }

            float deltaYawDeg = Mathf.DeltaAngle(_lastHeadYawDeg, newHeadYawDeg);
            Quaternion dR = Quaternion.Euler(0f, deltaYawDeg, 0f);
            Vector3 dT = newHeadPos - dR * _lastHeadPos;

            calibrator.CompensateRawCorners(dR, dT);
            LogInfo($"Tracking origin change compensated (Δyaw {deltaYawDeg:0.##}°, Δpos {dT}); calibration re-applied.");
        }

        private bool TryGetHeadPoseInTrackingSpace(out Vector3 pos, out float yawDeg)
        {
            Camera cam = _xrOrigin?.Camera;
            if (cam == null)
            {
                pos = default;
                yawDeg = 0f;
                return false;
            }

            pos = transform.InverseTransformPoint(cam.transform.position);
            Vector3 fwd = transform.InverseTransformDirection(cam.transform.forward);
            fwd.y = 0f;
            // Looking straight up/down leaves yaw undefined, so we use last known value for this edge case
            yawDeg = fwd.sqrMagnitude < 1e-6f
                ? _lastHeadYawDeg
                : Mathf.Atan2(fwd.x, fwd.z) * Mathf.Rad2Deg;
            return true;
        }

        private void LateUpdate()
        {
            if (_originChangePending)
            {
                _originChangePending = false;
                CompensateOriginChange();
            }

            if (TryGetHeadPoseInTrackingSpace(out Vector3 headPos, out float headYawDeg))
            {
                _lastHeadPos = headPos;
                _lastHeadYawDeg = headYawDeg;
                _hasHeadPose = true;
            }
        }
    }
}
